name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - main

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Get short commit SHA for versioning
      - name: Extract short SHA
        id: vars
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Step 5: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Change this to root directory
          push: true
          tags: debasis1999/project-work:${{ env.SHA }}  # Versioned tag with commit SHA
          build-args: |
            SQL_USER_ID=${{ secrets.SQL_USER_ID }}
            SQL_DB_PASS=${{ secrets.SQL_DB_PASS }}
            SQL_DB_HOST=${{ secrets.SQL_DB_HOST }}
            SQL_DB_NAME=${{ secrets.SQL_DB_NAME }}
            SQL_DB_ENCRYPT=${{ secrets.SQL_DB_ENCRYPT }}

      # Step 6: Verify that the Docker image was built and pushed
      - name: Verify Docker image
        run: docker pull debasis1999/project-work:${{ env.SHA }}
